### PR TITLE
fix capitalization/typo in filename

### PR DESCRIPTION
**Pull request by seandavi**
PNG should be png.

### CODE REVIEW

**Comment by seandavi** [comment]
The vignette does not build without this small change, so if you can merge, that would really help. Thanks a bunch.

**Comment by seandavi** [comment]
@gabrielodom, could you take a moment to review and merge this request? As it stands, your workshop is not building and materials are not available on the Bioc AMI. Sorry to pester, but we want to finalize in the next few hours. Thanks!

**Comment by gabrielodom** [comment]
I’m so sorry about this. Give me a few minutes

**Comment by gabrielodom** [comment]
I am driving to work now

**Comment by gabrielodom** [comment]
@seandavi I fixed the issue directly (it checks and build on both Mac and Windows now), but now I'm having trouble resolving this pull request. Please forgive my ignorance with Git and GitHub.

**Comment by seandavi** [comment]
No problem. You fixed the problem--just closing. Thanks for the quick response!

**Comment by gabrielodom** [comment]
@seandavi I will be available to resolve any other issues for the next 6 hours.

**Comment by seandavi** [comment]
You are good-to-go. Installed and vignette built. Thanks again.

**Pull request closed without merging**
